# Working with tabular data

## Introducing `numpy`

In the last module you saw some of the limitations for quick quantiative analysis using built-in Python functionalities:

In [1]:
# It's hard to calculate on lists!
my_list = [4, 1, 5, 2]
my_list * 2

Fortunately you also learned about packages -- they'll come to our rescue!

Let's store these same numbers in what's called a `numpy` *array*. 

This involves importing the `numpy` package. 

`numpy` is short for "numerical Python."

Generally when we are using a package for the first time, we need to install it: 

However, `numpy` was installed already when we installed `pandas`. (These packages are also pre-installed with Anaconda).

We *do* still need to import `numpy` before using it: 

In [2]:
import numpy

We can use `numpy.array()` to create an array.

Arrays are collections of data enclosed in brackets `[]`. Unlike with lists, all elements of the array *need to be of the same type*.



In [3]:
# Create an array
my_array = numpy.array([4, 1, 5, 2])
my_array

array([4, 1, 5, 2])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
# This is an example of type coercion
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

Lists and arrays may *look* the same to you, but they are of different types.

In [6]:
my_list
type(my_list)

list

In [7]:
my_list_to_array = numpy.array(my_list)
type(my_list_to_array)

numpy.ndarray

`numpy` arrays work in many ways like ranges of a spreadsheet...

In [8]:
my_array

array([4, 1, 5, 2])

In [9]:
# Isn't this what you were expecting earlier?
my_array * 2

array([ 8,  2, 10,  4])

Based on what we're seeing, we may want to be calling for `numpy` *quite* often. 

Let's look at a cool "hack" for doing so...

### Aliasing modules

Remember that each time we use a function or method associated with `numpy`, we need to tell Python where to look for it: 

In [10]:
# Create another array...
my_other_array = numpy.array([4, 16, 25, 100])

# numpy has a square root function of its own...
numpy.sqrt(my_other_array)

array([ 2.,  4.,  5., 10.])

I am already getting sick of typing `numpy` each time I want to use something from it! Can't we make this easier?

Yes. Yes, we can.

Turns out we can temporarily rename, or *alias*, the `numpy` module when we import it. We will use the format:


```
import [name of module] as [alias]
```

`np` is a popular alias for `numpy`. Rather than calling for `numpy` each time you are using code from that module, you can simply type `np`. 



In [11]:
# Alias numpy on import
import numpy as np

# Create another array...
my_other_array = np.array([4,16,25,100])

# numpy has a square root function of its own...
np.sqrt(my_other_array)

array([ 2.,  4.,  5., 10.])

### Drill

Take a shot at assigning an array and finding its square root using this aliasing method. 

In [12]:
# Import and alias the module

import ___ ___ ___

# Create an array
my_new_array = ___.___([36, 49, 64, 81])

# Take its square root
np.___(___)

SyntaxError: invalid syntax (<ipython-input-12-a1711e16e71e>, line 3)

Aliasing saved you some keystrokes, huh?

![Life hackz](images/life-hackz.gif)

## Accessing and reshaping arrays

Python indexes *everything* at zero, not just lists. This includes `numpy` arrays!

In [14]:
my_array = np.array([4, 1, 5, 2])

In [15]:
# Access first element of the array
my_array[1]

1

In [16]:
# Oh sorry... NOW I'm accessing the first element! 🤦‍♂️
my_array[0]

4

You've already sweated through zero-based indexing, so let's move on... to two-dimensional arrays. 

(You will see that you'll never truly escape zero-based indexing in Python, however... 😼)

## Two-dimensional arrays in `numpy`

So far, we have been working on one-dimensional sets of data. 

You can think of this as data being in one row or column of your workbook.

But what if we wanted to mix that up? 

![Illustration of numpy arrays](images/numpy-arrays.png)



Source: Nunez-Iglesias, Juan, Stéfan Van Der Walt, and Harriet Dashnow. *Elegant SciPy: The Art of Scientific Python.* O'Reilly Media, 2017.


`numpy` can create up to _n_-dimensional arrays. You can think of one, two, and three-dimensional arrays as being like individual ranges, tables, and worksheets in Excel.

In [17]:
# Create a two-dimensional array with `np.array()`

my_2d_array = np.array([[3, 4, 1], [2 ,5 ,0]])
type(my_2d_array)

numpy.ndarray

We can also re-shape an existing one-dimensional array into a two-dimensional array using `np.reshape()`

In [18]:
# One-dimensional array
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array


array([1, 2, 3, 4, 5, 6])

In [19]:
# Let's make a two-dimensional, 2 x 3 array
my_reshaped_array = np.reshape(my_array, (2, 3))
my_reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

A two-dimensional array is starting to look like the kind of dataset that you might actually work with as a spreadsheet user, with rows and columns.

## Inspecting our arrays

Variables in Python carry different `attributes` which we can find using the format 

`variable.attribute`


Some attributes we can use to learn more about our `numpy` arrays are:

`shape`: gives us the dimensions of the array.  


In [ ]:
my_reshaped_array.shape

`size`: gives us the number of elements of the array.   


In [ ]:
my_reshaped_array.size

`dtype`: gives us the data type of the elements of the array. Remember that all elements of a `numpy` array must be of the same type.

In [ ]:
my_reshaped_array.dtype

### Indexing and slicing our 2-dimensional arrays

Remember when I said that zero-based indexing never really goes away? I wasn't kidding. 

Now we have to index on *two* counts: the row and the column. Our indexing of two-dimensional `numpy` arrays will look like this 

`np_array[row_number, column_number]`

Some examples:



In [ ]:
# Get the value in first row, first column
# Never forget zero-based indexing!
my_reshaped_array[0, 0]

In [ ]:
# What about the second-last row/second-last column?
my_reshaped_array[-2, -2]

It's also possible to use slicing to retrive data from multiple rows and columns.

In [ ]:
# Get data from first through second rows and columns
my_reshaped_array[0:2, 0:2]

In [ ]:
# What about up through the second row and second column?
my_reshaped_array[:2, :2]

# DRILL

Practice your `numpy` skills by operating on a large array. 

I will get you started; complete the operations based on what the comments are asking for. 

In [ ]:
# Don't worry about this part -- I am reading the file into Python.
# You will learn how to read files into Python in the next unit. 
my_array = np.genfromtxt('numpy-drill.csv')
my_array

In [ ]:
# What is the shape of this array?
# This also tells us how many dimensions there are --
# one number means one dimension
my_array.___

In [ ]:
# What is its datatype?
___

In [ ]:
# Reshape this result into a 10x10 array
my_array = np.reshape(___, ___)

In [ ]:
# What is the shape of our array now?
___

In [ ]:
# Take the sqrt of this array
my_array = np.___(___)
my_array

In [ ]:
# Access the element in the fourth row
# and second column of the array
my_array___

# Questions about `numpy`?

# Working with `pandas`

When you think of "tabular data" in Python, think of `pandas`. 

This package is built on top of `numpy`, but brings some extra functionalities for us. 

Similarly to `numpy`, `pandas` contains data structure of different dimensions.


### `pandas` Series

These are one-dimensional data structures in `pandas`. 

We won't spend too much time analyzing these, but it's important to know that `pandas` will by default convert any one-dimensional data structure into a Series. 

*Notice the zero-based index? We'll get to that in a bit.*

![pandas Series](images/series.png)

### DataFrames

We will focus on the `pandas` DataFrame, which is a two-dimensional, tabular data structure with labeled rows and columns. Below is an example:

![`pandas` DataFrame example](images/dataframe.png)


*Look familiar?* This is very much the way we often store data in a spreadsheet.

One key difference between `numpy` arrays and  `pandas` DataFrames is that the columns of DataFrames can be of different data types:

![DataFrame column data types](images/datatypes.png)

This is a *lot* like a spreadsheet!

## Importing `pandas`

Same as with `numpy`, we will need to call in `pandas` each time we want to use it.

Similarly to `numpy`, it is common to *alias* `pandas` when we import it. This alias usually takes the form:

`import pandas as pd`

Go ahead and try it yourself in the cell below!

In [21]:
# Load pandas into our session
import pandas as pd

### Creating DataFrames

There are several ways to create a DataFrame. We could, for example, convert a `numpy` array into one, using the [`DataFrame` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

In [22]:
# Create our array
numpy_data = np.array([[1, 2, 3], [4, 5, 6]])

# Convert into a DataFrame
df = pd.DataFrame(data=numpy_data)
df

0  1  2
0  1  2  3
1  4  5  6

By default, our DataFrame includes column *names* and row *index labels*... **starting at zero**!

![labelled image of DataFrames](images/dataframe-labelled.png)

It's common to keep the index labels as numeric, but to name the columns. Let's do it:

In [23]:
# Create our array
numpy_data = np.array([[1, 2, 3], [4, 5, 6]])

# Convert into a DataFrame,# name the columns
df = pd.DataFrame(data=numpy_data, columns=['Column A','Column B','Column C'])
df

Column A  Column B  Column C
0         1         2         3
1         4         5         6

## Reading data into `pandas`

While it's possible to create a DataFrame from scratch or from an existing data structure (like a `numpy` array), you'll more likely do by importing data from an outside source. 

`pandas` can create DataFrames from practically any data format, including SQL databases and HTML. But let's focus on `csv` files and Excel workbooks.

### Reading from `csv` files

We can import a `csv` file as a DataFrame with `read_csv()`.

There are a *lot* of [optional arguments to provide `read_csv()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html), but we *must* provide a file path.


#### Interlude: file paths and directories

It can sometimes be tricky to locate *where* a file is located to read it into Python.

By default, the file path you specify needs to be *relative to* your working directory. If you aren't sure that working directory is set, you can check with `os.getcwd()`. 

You will need to run `import os` first (This is part of the Python standard library.).

In [24]:
import os

# What folder am I operating in on my computer?
os.getcwd()

'C:\\Users\\George Mount\\Documents\\GitHub\\python-for-excel-users-first-steps\\2-working-with-tabular-data'

In this case, the `state-populations.csv` file is located in the `data` subfolder of this directory, so we can find it here:

In [25]:
# Read in the state-populations file that exists in the data folder
pd.read_csv('data/state-populations.csv')

name  Year  Population  Density
0    Alabama  2010     4785492  50750.0
1    Alabama  2011     4799918  50750.0
2    Alabama  2012     4815960  50750.0
3    Alabama  2013     4829479  50750.0
4    Alabama  2014     4843214  50750.0
..       ...   ...         ...      ...
352  Wyoming  2012      576765  97105.0
353  Wyoming  2013      582684  97105.0
354  Wyoming  2014      583642  97105.0
355  Wyoming  2015      586555  97105.0
356  Wyoming  2016      585501  97105.0

[357 rows x 4 columns]

[For more on how to work with files and directories in Python, check out this book chapter](https://learning.oreilly.com/library/view/automate-the-boring/9781098122584/xhtml/ch09.xhtml).

That's nice we were able to read this into Python... but to do much of anything with it, we'll need to assign it to a variable:

In [26]:
# Read in csv as DataFrame, assign to variable
state_pop = pd.read_csv('data/state-populations.csv')

# Now I can refer to the variable and operate on it...
# This one isn't real helpful 😼
state_pop * 2

name  Year  Population   Density
0    AlabamaAlabama  4020     9570984  101500.0
1    AlabamaAlabama  4022     9599836  101500.0
2    AlabamaAlabama  4024     9631920  101500.0
3    AlabamaAlabama  4026     9658958  101500.0
4    AlabamaAlabama  4028     9686428  101500.0
..              ...   ...         ...       ...
352  WyomingWyoming  4024     1153530  194210.0
353  WyomingWyoming  4026     1165368  194210.0
354  WyomingWyoming  4028     1167284  194210.0
355  WyomingWyoming  4030     1173110  194210.0
356  WyomingWyoming  4032     1171002  194210.0

[357 rows x 4 columns]

### Reading from Excel

We'll now read in a file `state-populations.xlsx`, also located in the `data` folder.


Reading Excel workbooks into DataFrames will work similar to `csv` files. 

This time, we'll use `read_excel()`. 

Once again, there are [lots of optional arguments](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html), but we must provide a file path: 

In [27]:
# Read in our data
state_pop = pd.read_excel('data/state-populations.xlsx')
state_pop

name  Year  Population  Density
0    Alabama  2010     4785492  50750.0
1    Alabama  2011     4799918  50750.0
2    Alabama  2012     4815960  50750.0
3    Alabama  2013     4829479  50750.0
4    Alabama  2014     4843214  50750.0
..       ...   ...         ...      ...
352  Wyoming  2012      576765  97105.0
353  Wyoming  2013      582684  97105.0
354  Wyoming  2014      583642  97105.0
355  Wyoming  2015      586555  97105.0
356  Wyoming  2016      585501  97105.0

[357 rows x 4 columns]

If our workbook contains multiple worksheets and we want to read specific one(s), we would specify the `sheet_name` argument:

In [28]:
# Read the `populations` worksheet
state_pop = pd.read_excel('data/state-populations.xlsx', sheet_name='populations')
state_pop

name  Year  Population  Density
0    Alabama  2010     4785492  50750.0
1    Alabama  2011     4799918  50750.0
2    Alabama  2012     4815960  50750.0
3    Alabama  2013     4829479  50750.0
4    Alabama  2014     4843214  50750.0
..       ...   ...         ...      ...
352  Wyoming  2012      576765  97105.0
353  Wyoming  2013      582684  97105.0
354  Wyoming  2014      583642  97105.0
355  Wyoming  2015      586555  97105.0
356  Wyoming  2016      585501  97105.0

[357 rows x 4 columns]

In [29]:
# There is also a `readme` worksheet
readme = pd.read_excel('data/state-populations.xlsx',sheet_name='readme')
readme

Data sources:                                       Unnamed: 1
0     US Census  https://www.census.gov/prod/cen2010/cph-2-1.pdf

That second worksheet doesn't look much like a table of data... but `pandas` did its best to make it so! 

This is a good reminder that DataFrames will always be two-dimensional structures where all the rows in a given column are of the same data type, but different columns can be of different data types.

That's it for reading data from Excel. 

**If you are interested in using Python to automate the creation of Excel workbooks, check out my OLT session on "Python-Powered Excel."**

## Reading from Google Sheets

For many users, spreadsheets mean Google Sheets. 

It is possible to read DataFrames from Google Sheets but it requires using Google's API. Due to that added setup, we will skip for this workshop.

[For instructions on reading from Google Sheets, check out this book chapter.](https://learning.oreilly.com/library/view/automate-the-boring/9781098122584/xhtml/ch14.xhtml#ch14)


## Exploring our DataFrame

*Success*! Our data has been read in and assigned to a variable. Now let's get to know our data. 

We can of course get started by printing it: 


In [30]:
state_pop

name  Year  Population  Density
0    Alabama  2010     4785492  50750.0
1    Alabama  2011     4799918  50750.0
2    Alabama  2012     4815960  50750.0
3    Alabama  2013     4829479  50750.0
4    Alabama  2014     4843214  50750.0
..       ...   ...         ...      ...
352  Wyoming  2012      576765  97105.0
353  Wyoming  2013      582684  97105.0
354  Wyoming  2014      583642  97105.0
355  Wyoming  2015      586555  97105.0
356  Wyoming  2016      585501  97105.0

[357 rows x 4 columns]

However, this is a *lot* of rows to look through. It's so much that Python doesn't even print all of them! You could [change the options](https://dev.to/chanduthedev/how-to-display-all-rows-from-data-frame-using-pandas-dha) to print all rows, but that's really not an effective way to size up our DataFrame. 

Instead, let's use the below methods and attributes to explore more efficiently:

 

| Method/attribute | Returns                                                         |
| ---------------- | --------------------------------------------------------------- |
| `df.info()`      | Column names with their data type and number of complete values |
| `df.columns`     | Column names                                                    |
| `df.dtypes`      | Data types                                                      |
| `df.shape`       | Dimensions (# rows by # columns)                                |
| `df.head()`      | First 5 rows                                                    |
| `df.tail()`      | Last 5 rows                                                     |
| `df.describe()`  | Descriptive statistics                                          |


`df` is a common stand-in for a generic DataFrame which you'll often see in examples. 

Our DataFrame is named `state_pop`:

In [31]:
# Return column names, data types and number of complete values
state_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
name          357 non-null object
Year          357 non-null int64
Population    357 non-null int64
Density       350 non-null float64
dtypes: float64(1), int64(2), object(1)
memory usage: 11.3+ KB


Data types in `pandas` work a little differently than in base Python. For example, string types are classified as `object`. [For more on how `pandas` handles data types, check out this blog post](https://pbpython.com/pandas_dtypes.html).

In [32]:
# Return column names
state_pop.columns

Index(['name', 'Year', 'Population', 'Density'], dtype='object')

In [33]:
# Return data types
state_pop.dtypes

name           object
Year            int64
Population      int64
Density       float64
dtype: object

Data types or `dtypes` in `pandas` work a little differently than base Python. Here is the basic mapping (courtesy [Practical Business Python](https://pbpython.com/pandas_dtypes.html)):

| Pandas dtype  | Python type  | NumPy type                                                     | Usage                                        |
| ------------- | ------------ | -------------------------------------------------------------- | -------------------------------------------- |
| object        | str or mixed | string_, unicode_, mixed types                                 | Text or mixed numeric and non-numeric values |
| int64         | int          | int_, int8, int16, int32, int64, uint8, uint16, uint32, uint64 | Integer numbers                              |
| float64       | float        | float_, float16, float32, float64                              | Floating point numbers                       |
| bool          | bool         | bool_                                                          | True/False values                            |
| datetime64    | datetime     | datetime64[ns]                                                 | Date and time values                         |
| timedelta[ns] | NA           | NA                                                             | Differences between two datetimes            |
| category      | NA           | NA                                                             | Finite list of text values                   |




If you would like to learn more about dates & times in Python and `pandas`, [check out this book chapter](https://learning.oreilly.com/library/view/python-data-science/9781491912126/ch03.html#:-:text=Pandas%20was%20developed%20in%20t,ich%20we%20will%20discuss%20here%3A).

In [ ]:
# Return shape (no. of rows, no. of columns)
state_pop.shape

In [ ]:
# Get first 5 rows
state_pop.head()

In [ ]:
# Get first 12 rows
state_pop.head(12)

In [ ]:
# Get last 5 rows
state_pop.tail()

In [ ]:
# Get descriptive statistics
state_pop.describe()

# DRILL

Practice reading in and exploring the two files in the `practice` folder.

1. `largest-us-cities.csv`: Find the data types and dimensions of this DataFrame. Also print out the first five rows.
2. `chicago-big-ten.xlsx`: The worksheet you're interested in is called `alumni`. Get the column names and run the descriptive statistics.

Congratulations on reading and exploring data in `pandas`! In the following sections we'll look at manipulating DataFrames and then visualizing the results. 